import { callGroqApi } from '../services/apiClient';

export const EXECUTION_AGENT_SYSTEM_PROMPT = `
You are the Execution Agent and Master Orchestrator. Your role is to finalize approved workflows and maintain the closed-loop learning cycle.

Your Responsibilities:
1. Receive validated and APPROVED allocation plans from the Validation Agent.
2. Simulate interactions with enterprise execution systems (ERP/WMS) to generate official records:
   - Create Transfer Orders (e.g., #TR-89213).
   - Update purchase order quantities or shipment priorities.
3. Write execution results back into the Gold lakehouse (gold_allocation_plan / gold_agent_decision_log) so dashboards and analytics tables update in real time.
4. Log outcome metrics (forecast vs. actual sales) to feed continuous learning loops for future model improvements.

Strict Rules:
- Never execute any plan that has not received explicit APPROVAL from the Validation Agent or Human-in-the-Loop reviewer.
- Provide clear confirmation messages to the user interface once actions are successfully committed.
- ONLY output valid JSON format, with no markdown formatting or extra text.
`;

export interface ExecutionInput {
  allocation_plan: any; // The original plan generated by the Allocation Agent
  validation_status: "APPROVED" | "REJECTED" | "PENDING_HUMAN_REVIEW";
  human_override_status?: "APPROVED" | "REJECTED"; // If a human stepped in
}

/**
 * Invokes the Execution Agent using Groq
 */
export const runExecutionAgent = async (inputData: ExecutionInput) => {
  // Pre-execution deterministic check (Guardrail enforcement)
  const isApproved = inputData.validation_status === "APPROVED" || inputData.human_override_status === "APPROVED";
  
  if (!isApproved) {
    throw new Error("Execution Agent Error: Cannot execute unapproved plans. Validation Status: " + inputData.validation_status);
  }

  const userPrompt = `
    Execute the following approved allocation plan and generate the simulated ERP records and success messages.
    
    Data:
    ${JSON.stringify(inputData, null, 2)}
    
    Please output a JSON object containing:
    {
      "transfer_order_id": "e.g. TR-89213",
      "records_updated": ["gold_allocation_plan", "gold_agent_decision_log", "ERP_WMS_Transfer"],
      "ui_confirmation_message": "String message to display to the user",
      "learning_loop_metrics_logged": true
    }
  `;

  const messages = [
    { role: "system", content: EXECUTION_AGENT_SYSTEM_PROMPT },
    { role: "user", content: userPrompt }
  ];

  try {
    const response = await callGroqApi(messages, "qwen/qwen3.8-27b");
    
    // Attempt to parse the JSON response
    const agentContent = response.choices[0].message.content;
    const parsedJson = JSON.parse(agentContent);
    return parsedJson;
  } catch (error) {
    console.error("Execution Agent failed:", error);
    throw error;
  }
};
